Code/IDM/IDM.Web-MVC/Models/ErrorViewModel.cs
namespace IDM.Web_MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Code/IDM/IDM.Web-MVC/Models/SecurityGroupViewModel.cs
using IDM.Business.Models.DTOs;

namespace IDM.Web_MVC.Models
{
    public class SecurityGroupViewModel
    {
        public List<SecurityGroupDTO> sgList { get; set; }
        public SecurityGroupDTO sgInfo { get; set; }
    }
}

Code/IDM/IDM.Web-MVC/Controllers/HomeController.cs
using IDM.Web_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace IDM.Web_MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Code/IDM/IDM.Web-MVC/Controllers/SecurityGroupController.cs
using IDM.Business.Contractors;
using IDM.Business.Models.DTOs;
using IDM.Web_MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace IDM.Web_MVC.Controllers
{
    public class SecurityGroupController : Controller
    {
        private readonly ISecurityGroupService _sg;
        public SecurityGroupController(ISecurityGroupService sg)
        {
            _sg = sg;
        }

        public async Task<IActionResult> Index()
        {
            var result = await _sg.GetSGsAsync();

            var model = new SecurityGroupViewModel
            {
                sgList = result.ToList(),
            };

            return View(model);
        }

        public async Task<IActionResult> CreateSG()
        {
            var model = new SecurityGroupViewModel()
            {
                sgInfo = new SecurityGroupDTO()
            };
            return View(model);
        }

        public async Task<IActionResult> EditSG(Guid internalID)
        {
            var model = new SecurityGroupViewModel()
            {
                sgInfo = await _sg.GetSGByIDAsync(internalID),
            };
            return View(model);
        }
    }
}

Code/IDM/IDM.Web-MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

@*Security Group Management*@
<div class="row mb-4">
    <div class="cstm-mng-header">
        <span>Security Group Management</span>
    </div>
    <div class="row">
        <div class="col-12 col-sm-6 col-md-4 col-lg-2">
            <a class="cstm-mng-button" asp-area="" asp-controller="SecurityGroup">
                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-collection-fill" viewBox="0 0 16 16">
                    <path d="M0 13a1.5 1.5 0 0 0 1.5 1.5h13A1.5 1.5 0 0 0 16 13V6a1.5 1.5 0 0 0-1.5-1.5h-13A1.5 1.5 0 0 0 0 6v7zM2 3a.5.5 0 0 0 .5.5h11a.5.5 0 0 0 0-1h-11A.5.5 0 0 0 2 3zm2-2a.5.5 0 0 0 .5.5h7a.5.5 0 0 0 0-1h-7A.5.5 0 0 0 4 1z" />
                </svg>
                My <br />
                Security Group(s)
            </a>
        </div>
    </div>
</div>

@*Computer Management*@
<div class="row mb-4">
    <div class="cstm-mng-header">
        Computer Management
    </div>

    <div class="row">
        <div class="col-12 col-sm-6 col-md-4 col-lg-2">
            <a class="cstm-mng-button" asp-area="" asp-controller="Home" asp-action="Privacy">
                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-pc-display-horizontal" viewBox="0 0 16 16">
                    <path d="M1.5 0A1.5 1.5 0 0 0 0 1.5v7A1.5 1.5 0 0 0 1.5 10H6v1H1a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-3a1 1 0 0 0-1-1h-5v-1h4.5A1.5 1.5 0 0 0 16 8.5v-7A1.5 1.5 0 0 0 14.5 0h-13Zm0 1h13a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-7a.5.5 0 0 1 .5-.5ZM12 12.5a.5.5 0 1 1 1 0 .5.5 0 0 1-1 0Zm2 0a.5.5 0 1 1 1 0 .5.5 0 0 1-1 0ZM1.5 12h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1ZM1 14.25a.25.25 0 0 1 .25-.25h5.5a.25.25 0 1 1 0 .5h-5.5a.25.25 0 0 1-.25-.25Z" />
                </svg>
                Computer <br />
                Account(s)
            </a>
        </div>
    </div>
</div>

@*Mailbox Management*@
<div class="row mb-4">
    <div class="cstm-mng-header">
        Mailbox Management
    </div>
    <div class="row">
        <div class="col-12 col-sm-6 col-md-4 col-lg-2">
            <a class="cstm-mng-button" asp-area="" asp-controller="Home" asp-action="Privacy">
                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-mailbox" viewBox="0 0 16 16">
                    <path d="M4 4a3 3 0 0 0-3 3v6h6V7a3 3 0 0 0-3-3zm0-1h8a4 4 0 0 1 4 4v6a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V7a4 4 0 0 1 4-4zm2.646 1A3.99 3.99 0 0 1 8 7v6h7V7a3 3 0 0 0-3-3H6.646z" />
                    <path d="M11.793 8.5H9v-1h5a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.354-.146l-.853-.854zM5 7c0 .552-.448 0-1 0s-1 .552-1 0a1 1 0 0 1 2 0z" />
                </svg>
                Shared <br />
                Mailbox
            </a>
        </div>
        <div class="col-12 col-sm-6 col-md-4 col-lg-2">
            <a class="cstm-mng-button" asp-area="" asp-controller="Home" asp-action="Privacy">
                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-mailbox" viewBox="0 0 16 16">
                    <path d="M4 4a3 3 0 0 0-3 3v6h6V7a3 3 0 0 0-3-3zm0-1h8a4 4 0 0 1 4 4v6a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V7a4 4 0 0 1 4-4zm2.646 1A3.99 3.99 0 0 1 8 7v6h7V7a3 3 0 0 0-3-3H6.646z" />
                    <path d="M11.793 8.5H9v-1h5a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.354-.146l-.853-.854zM5 7c0 .552-.448 0-1 0s-1 .552-1 0a1 1 0 0 1 2 0z" />
                </svg>
                Resource <br />
                Mailbox
            </a>
        </div>
    </div>
</div>

@*Account Management*@
<div class="row mb-4">
    <div class="cstm-mng-header">
        Account Management
    </div>
    <div class="row">
        <div class="col-12 col-sm-6 col-md-4 col-lg-2">
            <a class="cstm-mng-button" asp-area="" asp-controller="Home" asp-action="Privacy">
                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-person-gear" viewBox="0 0 16 16">
                    <path d="M11 5a3 3 0 1 1-6 0 3 3 0 0 1 6 0ZM8 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4Zm.256 7a4.474 4.474 0 0 1-.229-1.004H3c.001-.246.154-.986.832-1.664C4.484 10.68 5.711 10 8 10c.26 0 .507.009.74.025.226-.341.496-.65.804-.918C9.077 9.038 8.564 9 8 9c-5 0-6 3-6 4s1 1 1 1h5.256Zm3.63-4.54c.18-.613 1.048-.613 1.229 0l.043.148a.64.64 0 0 0 .921.382l.136-.074c.561-.306 1.175.308.87.869l-.075.136a.64.64 0 0 0 .382.92l.149.045c.612.18.612 1.048 0 1.229l-.15.043a.64.64 0 0 0-.38.921l.074.136c.305.561-.309 1.175-.87.87l-.136-.075a.64.64 0 0 0-.92.382l-.045.149c-.18.612-1.048.612-1.229 0l-.043-.15a.64.64 0 0 0-.921-.38l-.136.074c-.561.305-1.175-.309-.87-.87l.075-.136a.64.64 0 0 0-.382-.92l-.148-.045c-.613-.18-.613-1.048 0-1.229l.148-.043a.64.64 0 0 0 .382-.921l-.074-.136c-.306-.561.308-1.175.869-.87l.136.075a.64.64 0 0 0 .92-.382l.045-.148ZM14 12.5a1.5 1.5 0 1 0-3 0 1.5 1.5 0 0 0 3 0Z" />
                </svg>
                System <br />
                Account(s)
            </a>
        </div>
        <div class="col-12 col-sm-6 col-md-4 col-lg-2">
            <a class="cstm-mng-button" asp-area="" asp-controller="Home" asp-action="Privacy">
                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-person-badge" viewBox="0 0 16 16">
                    <path d="M6.5 2a.5.5 0 0 0 0 1h3a.5.5 0 0 0 0-1h-3zM11 8a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
                    <path d="M4.5 0A2.5 2.5 0 0 0 2 2.5V14a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2.5A2.5 2.5 0 0 0 11.5 0h-7zM3 2.5A1.5 1.5 0 0 1 4.5 1h7A1.5 1.5 0 0 1 13 2.5v10.795a4.2 4.2 0 0 0-.776-.492C11.392 12.387 10.063 12 8 12s-3.392.387-4.224.803a4.2 4.2 0 0 0-.776.492V2.5z" />
                </svg>
                Account <br />
                Details
            </a>
        </div>
    </div>
</div>

Code/IDM/IDM.Web-MVC/Views/SecurityGroup/CreateSG.cshtml
@model SecurityGroupViewModel
@{
    ViewData["Title"] = "Create Security Group";
}

Code/IDM/IDM.Web-MVC/Views/SecurityGroup/EditSG.cshtml
@model SecurityGroupViewModel
@{
    ViewData["Title"] = "Edit Security Group";
}
<div class="row mb-3">
    <div class="mb-2 col-12">
        <h5>
            Security Group Information
        </h5>
    </div>

    <div class="mb-3 col-12">
        @Html.Label("displayNames", "Security Group Display Name:", new { @class = "form-label" })
        <div class="d-inline-flex col-12">
            <input type="text" class="form-control me-2" id="txtDisplayName1" name="displayName">
            <input type="text" class="form-control me-2" id="txtDisplayName2" name="displayName">
            <input type="text" class="form-control me-2" id="txtDisplayName3" name="displayName">
            <input type="text" class="form-control"      id="txtDisplayName4" name="displayName">
        </div>
    </div>

    <div class="mb-3 col-6">
        @Html.LabelFor(m => m.sgInfo.DisplayName, new { @class = "form-label" })
        @Html.TextBoxFor(m => m.sgInfo.DisplayName, new { @class="form-control" })
        @Html.ValidationMessageFor(m => m.sgInfo.DisplayName, "", new { @class = "text-danger" })
    </div>

    <div class="mb-3 col-6">
        @Html.LabelFor(m => m.sgInfo.AliasName, new { @class = "form-label" })
        @Html.TextBoxFor(m => m.sgInfo.AliasName, new { @class="form-control" })
        @Html.ValidationMessageFor(m => m.sgInfo.AliasName, "", new { @class = "text-danger" })
    </div>
</div>

<div class="row">
    <div class="mb-2 col-12">
        <h5>
            Email Address Information
        </h5>
    </div>

    <div class="mb-3 col-6">
        @Html.LabelFor(m => m.sgInfo.IDMEmailAddress, new { @class = "form-label" })
        @Html.TextBoxFor(m => m.sgInfo.IDMEmailAddress, new { @class="form-control" })
        @Html.ValidationMessageFor(m => m.sgInfo.IDMEmailAddress, "", new { @class = "text-danger" })
    </div>

    <div class="mb-3 col-6">
        @Html.LabelFor(m => m.sgInfo.RegionalEmailAddress, new { @class = "form-label" })
        @Html.TextBoxFor(m => m.sgInfo.RegionalEmailAddress, new { @class="form-control" })
        @Html.ValidationMessageFor(m => m.sgInfo.RegionalEmailAddress, "", new { @class = "text-danger" })
    </div>
</div>

Code/IDM/IDM.Web-MVC/Views/SecurityGroup/Index.cshtml
@model SecurityGroupViewModel
@{
    ViewData["Title"] = "Security Group List";
}
<!-- Button trigger modal -->
<button type="button" class="btn btn-light btn-sm" data-bs-toggle="modal" data-bs-target="#exampleModal">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-funnel" viewBox="0 0 16 16">
        <path d="M1.5 1.5A.5.5 0 0 1 2 1h12a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.128.334L10 8.692V13.5a.5.5 0 0 1-.342.474l-3 1A.5.5 0 0 1 6 14.5V8.692L1.628 3.834A.5.5 0 0 1 1.5 3.5v-2zm1 .5v1.308l4.372 4.858A.5.5 0 0 1 7 8.5v5.306l2-.666V8.5a.5.5 0 0 1 .128-.334L13.5 3.308V2h-11z"/>
    </svg>
    Filter
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<div id="data">
    <table class="cstm-table">
        <thead>
            <tr>
                <th>Action</th>
                <th>AliasName</th>
                <th>DisplayName</th>
                <th>Owner</th>
                <th>Admin 1</th>
                <th>Admin 2</th>
                <th>Admin 3</th>
                <th>Mail Address</th>
                <th>Status</th>
                <th>Created Date</th>
                <th>Modified Date</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.sgList == null || Model.sgList.Count == 0)
            {
                <tr>
                    <td class="cstm-text-center" colspan="11">
                        No records found in the system.
                    </td>
                </tr>
            }
            else
            {
                @foreach (var sg in Model.sgList)
                {
                    <tr>
                        <td>@sg.AliasName</td>
                        <td>@sg.DisplayName</td>
                        <td>@sg.OwnerName</td>
                        <td>@sg.Admin1Name</td>
                        <td>@sg.Admin2Name</td>
                        <td>@sg.Admin3Name</td>
                        <td>@sg.PrimaryEmailAddress</td>
                        <td>@sg.TypeDescription</td>
                        <td>@sg.StatusDescription</td>
                        <td>@sg.CreatedDate.ToShortDateString()</td>
                        <td>@sg.ModifiedDate?.ToShortDateString()</td>
                        <td>@Html.ActionLink("Edit", "EditSG", "SecurityGroup", new { internalID = sg.InternalID })</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

<script type="text/javascript" src="~/js/Group/Index.js"></script>

Code/IDM/IDM.Web-MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IDM.Web_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IDM.Web_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @Html.ActionLink("IDM Web", "Index", "Home", null, new { @class = "navbar-brand" })
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            @Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link text-dark" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Privacy", "Privacy", "Home", null, new { @class = "nav-link text-dark" })
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - IDM.Web_MVC - 
            @Html.ActionLink("Privacy", "Privacy", "Home")
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>